[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
fxhash = "0.2.1"
itertools = "0.13.0"
nom = "7.1.3"
reqwest = { version = "0.12.9", features = ["blocking", "cookies"] }
